# Generated by Django 6.0.6 on 2026-06-28 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bite_cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("animal_owner_name", models.CharField(blank=True, max_length=200)),
                ("owner_contact", models.CharField(blank=True, max_length=20)),
                ("animal_location", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("observation_notes", models.TextField(blank=True)),
                ("daily_status", models.TextField(blank=True)),
                (
                    "final_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("healthy", "Healthy after observation"),
                            ("sick", "Sick"),
                            ("died", "Died"),
                            ("missing", "Missing"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("final_remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bite_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observation",
                        to="bite_cases.animalbitecase",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FollowUpRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follow_up_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("missed", "Missed"),
                            ("rescheduled", "Rescheduled"),
                            ("contacted", "Contacted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bite_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="bite_cases.animalbitecase",
                    ),
                ),
                (
                    "contacted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-follow_up_date"],
            },
        ),
        migrations.CreateModel(
            name="VaccinationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rig_given", models.BooleanField(default=False)),
                ("tetanus_toxoid_given", models.BooleanField(default=False)),
                ("antibiotics_given", models.BooleanField(default=False)),
                ("other_medicine", models.TextField(blank=True)),
                ("doctor_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bite_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_schedule",
                        to="bite_cases.animalbitecase",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VaccineDose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dose_label", models.CharField(max_length=50)),
                ("scheduled_date", models.DateField()),
                ("actual_date", models.DateField(blank=True, null=True)),
                ("vaccine_brand", models.CharField(blank=True, max_length=100)),
                ("batch_number", models.CharField(blank=True, max_length=100)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "dose_status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("missed", "Missed"),
                            ("rescheduled", "Rescheduled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administered_doses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doses",
                        to="vaccination.vaccinationschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date"],
            },
        ),
    ]
