# Generated by Django 6.0.6 on 2026-08-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bite_cases", "0001_initial"),
        ("patients", "0002_patient_account"),
        ("vaccination", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("3days_before", "3 Days Before"),
                            ("on_day", "On Day"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipient", models.CharField(max_length=30)),
                ("message", models.TextField()),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("semaphore_message_id", models.CharField(blank=True, max_length=100)),
                ("api_response", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bite_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_logs",
                        to="bite_cases.animalbitecase",
                    ),
                ),
                (
                    "dose",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_logs",
                        to="vaccination.vaccinedose",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_logs",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["scheduled_date", "reminder_type"],
                        name="vaccination_schedul_dc59a8_idx",
                    ),
                    models.Index(
                        fields=["recipient"], name="vaccination_recipie_8724ac_idx"
                    ),
                ],
            },
        ),
    ]
