# Generated by Django 6.0.6 on 2026-06-28 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalBiteCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_number", models.CharField(max_length=20, unique=True)),
                ("date_time_bite", models.DateTimeField()),
                ("date_time_consultation", models.DateTimeField(auto_now_add=True)),
                ("place_of_incident", models.CharField(max_length=255)),
                ("incident_barangay", models.CharField(max_length=100)),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("dog", "Dog"),
                            ("cat", "Cat"),
                            ("monkey", "Monkey"),
                            ("bat", "Bat"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("animal_other", models.CharField(blank=True, max_length=100)),
                (
                    "animal_ownership",
                    models.CharField(
                        choices=[
                            ("owned", "Owned"),
                            ("stray", "Stray"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "animal_vax_status",
                    models.CharField(
                        choices=[
                            ("vaccinated", "Vaccinated"),
                            ("not_vaccinated", "Not Vaccinated"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "animal_condition",
                    models.CharField(
                        choices=[
                            ("alive", "Alive"),
                            ("dead", "Dead"),
                            ("missing", "Missing"),
                            ("under_observation", "Under Observation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "exposure_type",
                    models.CharField(
                        choices=[
                            ("bite", "Bite"),
                            ("scratch", "Scratch"),
                            ("lick", "Lick on broken skin"),
                            ("saliva", "Contact with saliva"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("body_part_affected", models.CharField(max_length=255)),
                ("number_of_wounds", models.IntegerField(default=1)),
                ("wound_description", models.TextField(blank=True)),
                ("wound_washed_immediately", models.BooleanField(default=False)),
                ("first_aid_given", models.TextField(blank=True)),
                ("initial_consultation_notes", models.TextField(blank=True)),
                (
                    "case_status",
                    models.CharField(
                        choices=[
                            ("new", "New Case"),
                            ("under_treatment", "Under Treatment"),
                            ("completed", "Completed"),
                            ("missed", "Missed Appointment"),
                            ("referred", "Referred"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bite_cases",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExposureClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("category_i", "Category I"),
                            ("category_ii", "Category II"),
                            ("category_iii", "Category III"),
                        ],
                        max_length=20,
                    ),
                ),
                ("classification_date", models.DateTimeField(auto_now_add=True)),
                ("medical_notes", models.TextField(blank=True)),
                ("recommended_action", models.TextField(blank=True)),
                ("treatment_plan", models.TextField(blank=True)),
                (
                    "bite_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposure",
                        to="bite_cases.animalbitecase",
                    ),
                ),
                (
                    "classified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bite_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_notes",
                        to="bite_cases.animalbitecase",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
