# Generated by Django 6.0.6 on 2026-08-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("health_worker", "Health Worker / ABTC Staff"),
                    ("doctor", "Doctor / Nurse"),
                    ("encoder", "Encoder"),
                    ("patient", "Patient"),
                ],
                default="encoder",
                max_length=20,
            ),
        ),
    ]
