# Generated by Django 6.0.6 on 2026-06-28 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplyInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supply_name", models.CharField(max_length=200)),
                (
                    "supply_type",
                    models.CharField(
                        choices=[
                            ("syringe", "Syringe"),
                            ("cotton", "Cotton"),
                            ("alcohol", "Alcohol"),
                            ("gloves", "Gloves"),
                            ("forms", "Forms"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("unit", models.CharField(default="piece", max_length=50)),
                ("reorder_level", models.IntegerField(default=10)),
                ("source_supplier", models.CharField(blank=True, max_length=200)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Supply Inventory",
                "ordering": ["supply_name"],
            },
        ),
        migrations.CreateModel(
            name="VaccineInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vaccine_name", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=200)),
                ("batch_number", models.CharField(max_length=100)),
                ("expiration_date", models.DateField()),
                ("quantity_received", models.IntegerField(default=0)),
                ("quantity_available", models.IntegerField(default=0)),
                ("quantity_used", models.IntegerField(default=0)),
                ("source_supplier", models.CharField(blank=True, max_length=200)),
                ("date_received", models.DateField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vaccine Inventory",
                "ordering": ["-date_received"],
            },
        ),
        migrations.CreateModel(
            name="VaccineStockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("stock_in", "Stock In"), ("stock_out", "Stock Out")],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference case number or note",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "moved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.vaccineinventory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
