# Generated by Django 6.0.6 on 2026-06-29 00:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bite_cases", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pre_registration_number",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("qr_code", models.TextField(blank=True)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("suffix", models.CharField(blank=True, max_length=20)),
                ("birthdate", models.DateField()),
                ("age", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("contact_number", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("barangay", models.CharField(max_length=100)),
                ("guardian_name", models.CharField(blank=True, max_length=200)),
                (
                    "guardian_contact_number",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "emergency_contact_number",
                    models.CharField(blank=True, max_length=20),
                ),
                ("bite_datetime", models.DateTimeField()),
                ("incident_place", models.CharField(max_length=255)),
                ("incident_barangay", models.CharField(max_length=100)),
                (
                    "animal_type",
                    models.CharField(
                        choices=[
                            ("dog", "Dog"),
                            ("cat", "Cat"),
                            ("monkey", "Monkey"),
                            ("bat", "Bat"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "animal_ownership",
                    models.CharField(
                        choices=[
                            ("owned", "Owned"),
                            ("stray", "Stray"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "animal_vaccination_status",
                    models.CharField(
                        choices=[
                            ("vaccinated", "Vaccinated"),
                            ("not_vaccinated", "Not Vaccinated"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "animal_condition",
                    models.CharField(
                        choices=[
                            ("alive", "Alive"),
                            ("dead", "Dead"),
                            ("missing", "Missing"),
                            ("under_observation", "Under Observation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "exposure_type",
                    models.CharField(
                        choices=[
                            ("bite", "Bite"),
                            ("scratch", "Scratch"),
                            ("lick", "Lick on broken skin"),
                            ("saliva", "Contact with saliva"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("body_part_affected", models.CharField(max_length=255)),
                ("number_of_wounds", models.PositiveIntegerField(default=1)),
                ("wound_washed", models.BooleanField(default=False)),
                ("first_aid_given", models.TextField(blank=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("for_verification", "For Verification"),
                            ("verified", "Verified"),
                            ("converted", "Converted to Official Case"),
                            ("cancelled", "Cancelled"),
                            ("duplicate", "Duplicate"),
                            ("no_show", "No Show"),
                        ],
                        default="submitted",
                        max_length=30,
                    ),
                ),
                ("consent_given", models.BooleanField(default=False)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "converted_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_pre_registrations",
                        to="bite_cases.animalbitecase",
                    ),
                ),
                (
                    "converted_patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_pre_registrations",
                        to="patients.patient",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_pre_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["pre_registration_number"],
                        name="pre_registr_pre_reg_a44aad_idx",
                    ),
                    models.Index(
                        fields=["status", "submitted_at"],
                        name="pre_registr_status_06d6e9_idx",
                    ),
                    models.Index(
                        fields=["barangay"], name="pre_registr_baranga_115709_idx"
                    ),
                ],
            },
        ),
    ]
