# Generated by Django 6.0.6 on 2026-08-27 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bite_cases", "0001_initial"),
        ("patients", "0003_add_vitalsign"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encounter_date", models.DateTimeField(auto_now_add=True)),
                (
                    "chief_complaint",
                    models.TextField(
                        blank=True, help_text="Chief complaint - patient's main concern"
                    ),
                ),
                (
                    "history_present_illness",
                    models.TextField(
                        blank=True, help_text="History of present illness - narrative"
                    ),
                ),
                (
                    "exposure_narrative",
                    models.TextField(
                        blank=True,
                        help_text="Detailed exposure narrative as verified by doctor",
                    ),
                ),
                (
                    "animal_type_verified",
                    models.CharField(
                        blank=True, help_text="Verified animal type", max_length=20
                    ),
                ),
                (
                    "animal_owned_verified",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("owned", "Owned"),
                            ("stray", "Stray"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "animal_vax_verified",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vaccinated", "Vaccinated"),
                            ("not_vaccinated", "Not Vaccinated"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "wound_washed_verified",
                    models.BooleanField(
                        blank=True, help_text="Wound washed immediately?", null=True
                    ),
                ),
                ("body_part_verified", models.CharField(blank=True, max_length=255)),
                (
                    "number_of_wounds_verified",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "date_time_bite_verified",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("exam_heent", models.TextField(blank=True, verbose_name="HEENT")),
                (
                    "exam_chest_lungs",
                    models.TextField(blank=True, verbose_name="Chest / Lungs"),
                ),
                ("exam_cardiac", models.TextField(blank=True, verbose_name="Cardiac")),
                ("exam_abdomen", models.TextField(blank=True, verbose_name="Abdomen")),
                (
                    "skin_wound_description",
                    models.TextField(
                        blank=True, help_text="Detailed skin / wound description"
                    ),
                ),
                (
                    "systemic_review",
                    models.TextField(blank=True, help_text="Systemic review notes"),
                ),
                (
                    "category_confirmed",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "category_i",
                                "Category I - Touching/feeding animal, licks on intact skin",
                            ),
                            (
                                "category_ii",
                                "Category II - Nibbling, minor scratches without bleeding",
                            ),
                            (
                                "category_iii",
                                "Category III - Transdermal bites/scratches, licks on broken skin, bat exposure",
                            ),
                        ],
                        help_text="WHO Bite Category confirmed by doctor",
                        max_length=20,
                    ),
                ),
                (
                    "pep_indicated",
                    models.BooleanField(default=False, verbose_name="PEP Indicated"),
                ),
                (
                    "rig_indicated",
                    models.BooleanField(default=False, verbose_name="RIG Indicated"),
                ),
                (
                    "tt_indicated",
                    models.BooleanField(default=False, verbose_name="TT Indicated"),
                ),
                (
                    "vaccine_brand_plan",
                    models.CharField(
                        blank=True,
                        help_text="Vaccine brand / lot planned",
                        max_length=100,
                    ),
                ),
                (
                    "dose_schedule_plan",
                    models.TextField(
                        blank=True, help_text="Dose schedule - e.g., Days 0,3,7,14,28"
                    ),
                ),
                (
                    "treatment_plan",
                    models.TextField(
                        blank=True, help_text="Detailed treatment & management plan"
                    ),
                ),
                (
                    "prescription",
                    models.TextField(
                        blank=True, help_text="Prescription / medications"
                    ),
                ),
                (
                    "follow_up_instructions",
                    models.TextField(blank=True, help_text="Follow-up instructions"),
                ),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True, help_text="Additional notes / allergy re-check"
                    ),
                ),
                (
                    "prc_number",
                    models.CharField(
                        blank=True, help_text="PRC License No.", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("final", "Final - Signed")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "is_finalized",
                    models.BooleanField(
                        default=False, help_text="Finalized and signed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bite_case",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_assessment",
                        to="bite_cases.animalbitecase",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_assessments",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinical Assessment",
                "verbose_name_plural": "Clinical Assessments",
                "ordering": ["-encounter_date", "-created_at"],
            },
        ),
    ]
