# Generated by Django 6.0.6 on 2026-08-27 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(help_text='When vitals were taken')),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='BP Systolic (mmHg)')),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='BP Diastolic (mmHg)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature (°C)')),
                ('pulse_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pulse Rate (bpm)')),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Respiratory Rate (/min)')),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='SpO₂ (%)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height (cm)')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='BMI')),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pain Score (0-10)')),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Blood Glucose (mg/dL)')),
                ('glucose_type', models.CharField(blank=True, choices=[('', '—'), ('random', 'Random'), ('fasting', 'Fasting')], default='', max_length=10)),
                ('general_appearance', models.CharField(blank=True, choices=[('', '—'), ('well', 'Well'), ('ill', 'Ill'), ('toxic', 'Toxic')], default='', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Allergy re-check or other notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patient')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vital Sign',
                'verbose_name_plural': 'Vital Signs',
                'ordering': ['-taken_at', '-created_at'],
            },
        ),
    ]
